id: PF52FA1ED
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN10628
  title: རྫོགས་རིམ་རིམ་ལྔ་གསལ་སྒྲོན།
  volumes:
    a0041da3c7c04a648cf5e9aa9186da75:
      image_group_id: I3CN10630
      title: ''
      base_file: v001.txt
  author: ''
